import React from "react";
import {
  Box,
  Typography,
  Paper,
  Button,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  Chip,
  Tooltip,
  Divider,
} from "@mui/material";
import { Send, CheckCircle, ErrorOutline } from "@mui/icons-material";

const AckVisualizer = ({ packetType, imei, index, alarm = 0 }) => {
  // Generate ACK packet based on packet type and data
  const generateACKPacket = () => {
    // ACK structure: [Header][Type][Length][Index][IMEI][Alarm?]
    const header = 0x2323; // Default header
    const lengthWithoutAlarm = 15; // 2+1+2+2+8 = 15 bytes
    const lengthWithAlarm = 16; // +1 for alarm byte
    const length = alarm > 0 ? lengthWithAlarm : lengthWithoutAlarm;

    const ackBytes = [];
    // Header (2 bytes)
    ackBytes.push((header >> 8) & 0xff);
    ackBytes.push(header & 0xff);

    // Type (1 byte) - same as packet type
    ackBytes.push(packetType);

    // Length (2 bytes)
    ackBytes.push((length >> 8) & 0xff);
    ackBytes.push(length & 0xff);

    // Index (2 bytes)
    ackBytes.push((index >> 8) & 0xff);
    ackBytes.push(index & 0xff);

    // IMEI (8 bytes ASCII)
    for (let i = 0; i < Math.min(imei.length, 8); i++) {
      ackBytes.push(imei.charCodeAt(i));
    }
    // Pad IMEI if less than 8 characters
    for (let i = imei.length; i < 8; i++) {
      ackBytes.push(0x00); // Null padding
    }

    // Alarm byte (if present)
    if (alarm > 0) {
      ackBytes.push(alarm);
    }

    return ackBytes;
  };

  const ackPacket = generateACKPacket();

  return (
    <Paper elevation={3}>
      <Box p={3}>
        <Typography variant="h5" gutterBottom>
          ACK Response Generator
        </Typography>

        {/* Info */}
        <Box mb={3}>
          <Typography variant="body2" color="text.secondary">
            The ACK (Acknowledgement) packet is automatically generated by the
            parser to confirm successful packet reception. Its structure varies
            based on packet type and whether it contains alarm data.
          </Typography>
        </Box>

        {/* ACK Structure Visualization */}
        <Box mb={4} p={2} sx={{ bgcolor: "action.selected", borderRadius: 1 }}>
          <Typography variant="h6" gutterBottom>
            ACK Packet Structure
          </Typography>

          <Box sx={{ overflowX: "auto" }}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableField>Field</TableField>
                  <TableField>Bytes</TableField>
                  <TableField>Value</TableField>
                  <TableField>Description</TableField>
                </TableRow>
              </TableHead>
              <TableBody>
                {/* Header */}
                <TableRow sx={{ backgroundColor: "#e3f2fd" }}>
                  <TableCell>Header</TableCell>
                  <TableCell>2</TableCell>
                  <TableCell>
                    0x
                    {ackPacket
                      .slice(0, 2)
                      .map((b) => b.toString(16).padStart(2, "0"))
                      .join("")}
                  </TableCell>
                  <TableCell>Packet identifier (0x2323)</TableCell>
                </TableRow>

                {/* Type */}
                <TableRow sx={{ backgroundColor: "#f3e5f5" }}>
                  <TableCell>Packet Type</TableCell>
                  <TableCell>1</TableCell>
                  <TableCell>
                    0x{ackPacket[2].toString(16).toUpperCase()} ({ackPacket[2]})
                  </TableCell>
                  <TableCell>Echoes original packet type</TableCell>
                </TableRow>

                {/* Length */}
                <TableRow sx={{ backgroundColor: "#e8f5e9" }}>
                  <TableCell>Length</TableCell>
                  <TableCell>2</TableCell>
                  <TableCell>
                    0x
                    {ackPacket
                      .slice(3, 5)
                      .map((b) => b.toString(16).padStart(2, "0"))
                      .join("")}
                  </TableCell>
                  <TableCell>
                    Total ACK packet length ({ackPacket.length} bytes)
                  </TableCell>
                </TableRow>

                {/* Index */}
                <TableRow sx={{ backgroundColor: "#fff3e0" }}>
                  <TableCell>Index</TableCell>
                  <TableCell>2</TableCell>
                  <TableCell>
                    0x
                    {ackPacket
                      .slice(5, 7)
                      .map((b) => b.toString(16).padStart(2, "0"))
                      .join("")}
                  </TableCell>
                  <TableCell>Echoes packet sequence number</TableCell>
                </TableRow>

                {/* IMEI */}
                <TableRow sx={{ backgroundColor: "#fce4ec" }}>
                  <TableCell>IMEI</TableCell>
                  <TableCell>8</TableCell>
                  <TableCell>
                    {String.fromCharCode(...ackPacket.slice(7, 15)).replace(
                      /\0/g,
                      "·",
                    )}
                  </TableCell>
                  <TableCell>Device identifier (ASCII)</TableCell>
                </TableRow>

                {/* Alarm (if present) */}
                {alarm > 0 && (
                  <TableRow sx={{ backgroundColor: "#ffebee" }}>
                    <TableCell>Alarm</TableCell>
                    <TableCell>1</TableCell>
                    <TableCell>
                      0x
                      {ackPacket[ackPacket.length - 1]
                        .toString(16)
                        .toUpperCase()}{" "}
                      ({ackPacket[ackPacket.length - 1]})
                    </TableCell>
                    <TableCell>Alarm/event indicator</TableCell>
                  </TableRow>
                )}

                {/* Summary */}
                <TableRow
                  sx={{ backgroundColor: "#e0e0e0", fontWeight: "bold" }}
                >
                  <TableCell colSpan={2}>Total Length</TableCell>
                  <TableCell colSpan={2}>
                    {ackPacket.length} bytes
                    <Chip
                      label={alarm > 0 ? "With Alarm" : "No Alarm"}
                      size="small"
                      sx={{ ml: 1 }}
                    />
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </Box>
        </Box>

        {/* Raw Hex View */}
        <Box mb={4} p={2} sx={{ bgcolor: "action.selected", borderRadius: 1 }}>
          <Typography variant="h6" gutterBottom>
            Raw ACK Packet (Hexadecimal)
          </Typography>
          <Typography
            variant="body2"
            sx={{ fontFamily: "monospace", letterSpacing: "0.5px" }}
          >
            {ackPacket
              .map((b) => b.toString(16).toUpperCase().padStart(2, "0"))
              .join(" ")}
          </Typography>
          <Box mt={1} display="flex" justifyContent="space-between">
            <Button variant="outlined" size="small">
              Copy Hex
            </Button>
            <Button variant="outlined" size="small">
              Download as .hex
            </Button>
          </Box>
        </Box>

        {/* Explanation */}
        <Box p={2} sx={{ bgcolor: "action.selected", borderRadius: 1 }}>
          <Typography variant="h6" gutterBottom>
            How ACK Works
          </Typography>
          <Typography variant="body1">
            When the parser successfully processes a packet, it generates an ACK
            response to inform the sending device that the packet was received
            correctly. This prevents retransmission and ensures reliable
            communication.
          </Typography>
          <Box mt={2}>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
              Key Points:
            </Typography>
            <Typography variant="body2" sx={{ ml: 2 }}>
              • ACK is only sent for packets that require acknowledgment (GPS,
              Alarm, etc.)
            </Typography>
            <Typography variant="body2" sx={{ ml: 2 }}>
              • Header and packet type are echoed from the original packet
            </Typography>
            <Typography variant="body2" sx={{ ml: 2 }}>
              • IMEI is copied to identify which device is responding
            </Typography>
            <Typography variant="body2" sx={{ ml: 2 }}>
              • Alarm byte is included only if original packet contained alarm
              data
            </Typography>
            <Typography variant="body2" sx={{ ml: 2 }}>
              • Length field reflects the actual ACK packet size
            </Typography>
          </Box>
        </Box>
      </Box>
    </Paper>
  );
};

// Helper components for table styling
const TableField = ({ children }) => (
  <TableCell sx={{ fontWeight: "medium", color: "text.primary" }}>
    {children}
  </TableCell>
);

export default AckVisualizer;
